---
apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: x-chicken-egg-demo
spec:
  forProvider:
    location: us-east1
    initialClusterVersion: latest

---
apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: x-chicken-egg-demo
spec:
  forProvider:
    locations:
    - us-east1-b
    - us-east1-c
    - us-east1-d
    clusterRef:
      name: x-chicken-egg-demo
    initialNodeCount: 1
    config:
      preemptible: true
      machineType: e2-standard-2
      oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
    autoscaling:
      enabled: true
      minNodeCount: 1
      maxNodeCount: 10
    management:
      autoUpgrade: false
