---
apiVersion: v1
kind: Service
metadata:
  name: x-chicken-egg-svc
  namespace: x-chicken-egg-ns
spec:
  type: LoadBalancer
  selector:
    app: x-chicken-egg-demo-app
  ports:
  - port: 80
    targetPort: 80
